// <auto-generated />
using System;
using CuerpoSano.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuerpoSano.Infrastructure.Migrations
{
    [DbContext(typeof(CuerpoSanoDbContext))]
    [Migration("20251008201714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Carnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId")
                        .IsUnique();

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Miembro", b =>
                {
                    b.HasBaseType("CuerpoSano.Domain.Entities.Persona");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembresiaId")
                        .HasColumnType("int");

                    b.HasIndex("MembresiaId")
                        .IsUnique()
                        .HasFilter("[MembresiaId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Miembro");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Carnet", b =>
                {
                    b.HasOne("CuerpoSano.Domain.Entities.Miembro", "Miembro")
                        .WithOne("Carnet")
                        .HasForeignKey("CuerpoSano.Domain.Entities.Carnet", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Miembro", b =>
                {
                    b.HasOne("CuerpoSano.Domain.Entities.Membresia", "Membresia")
                        .WithOne("Miembro")
                        .HasForeignKey("CuerpoSano.Domain.Entities.Miembro", "MembresiaId");

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Membresia", b =>
                {
                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("CuerpoSano.Domain.Entities.Miembro", b =>
                {
                    b.Navigation("Carnet");
                });
#pragma warning restore 612, 618
        }
    }
}
